version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=DOANVANHIEP
      - MINIO_ROOT_PASSWORD=0366830063
    ports:
      - '9092:9000'
      - '9001:9001'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  postgres_data: {}